// svelte/src/lib/Popover.svelte
<script lang="ts">
  import { onDestroy, onMount } from "svelte";
  import { cn } from "../utils";
  import Portal from "./Portal.svelte";
  import { upgradedSmartDropDown } from "../utils";
  import type {
    IPopOverPositionX,
    IPopOverPositionY,
  } from "../interface/general";

  export let isShown = false;
  export let width: string | undefined = undefined;
  export let className: string | undefined = undefined;
  export let onClickOutSide:
    | ((e: PointerEvent, handleClose: () => void) => void)
    | undefined = undefined;
  export let useRefWidth: boolean | undefined = undefined;
  export let zIndex: string | undefined = undefined;
  export let contentClassName: string | undefined = undefined;
  export let positionX: IPopOverPositionX | undefined = undefined;
  export let positionY: IPopOverPositionY | undefined = undefined;
  export let onClose = () => {};
  export let onOpen = () => {};

  let triggerElement: HTMLButtonElement | null = null;
  let popoverElement: HTMLDivElement | null = null;
  let top: string | undefined = undefined;
  let left: string | undefined = undefined;
  let delayShown = false;

  onMount(() => {
    document.addEventListener("keydown", handleKeyboardEvent);
    document.addEventListener("scroll", onScroll);
    window.addEventListener("resize", onScroll);
  });

  onDestroy(() => {
    document.removeEventListener("keydown", handleKeyboardEvent);
    document.removeEventListener("scroll", onScroll);
    window.removeEventListener("resize", onScroll);
  });

  $: {
    if (isShown) {
      setTimeout(() => {
        delayShown = true;
      }, 100);
    } else {
      delayShown = false;
    }
  }

  $: {
    if (delayShown) {
      positionDropDown({
        y: positionY || "auto",
        x: positionX || "center",
      });
    }
  }

  const handleKeyboardEvent = (e: KeyboardEvent) => {
    if (e.key === "Escape") {
      handleClose();
    }
  };

  const handleElementClick = () => {
    // if (handleChildrenClick) {
    //   handleChildrenClick(setIsShown || setShown);
    //   return;
    // }
    isShown = !isShown;
  };

  const positionDropDown = (position?: {
    x?: IPopOverPositionX;
    y?: IPopOverPositionY;
  }) => {
    if (!position) {
      position = {
        x: positionX || "center",
        y: positionY || "auto",
      };
    }
    const { left: lt, top: tp } = upgradedSmartDropDown({
      inputRef: triggerElement,
      dropDownRef: popoverElement,
      positionX: position.x,
      positionY: position.y,
    });
    top = tp;
    left = lt;
  };

  const onScroll = () => {
    if (!isShown) return;
    positionDropDown({
      y: positionY || "auto",
      x: positionX || "center",
    });
  };

  export const handleClose = () => {
    isShown = false;
  };
</script>

<div>
  <button
    style="width: {width || '100%'}"
    class={cn(className)}
    bind:this={triggerElement}
    on:click={handleElementClick}
  >
    <slot />
  </button>

  <Portal
    bind:isShown
    reference={triggerElement}
    hideDefaultStyle
    onClickOutside={onClickOutSide
      ? (e) => onClickOutSide?.(e, handleClose)
      : undefined}
    {useRefWidth}
    on:close={onClose}
    on:open={onOpen}
    style="z-index: {zIndex || '1000'}; position :fixed; {top
      ? `top: ${top};`
      : ''} {left ? `left: ${left};` : ''}"
  >
    <div
      class={cn(
        `
          rn-duration-350
          rn-transition-opacity
          rn-ease-in-out
          motion-reduce:rn-transition-none
        `,
        {
          "scale-100 rn-opacity-100": delayShown,
          "scale-90 rn-opacity-0": !delayShown,
        },
        contentClassName,
      )}
      bind:this={popoverElement}
    >
      <slot name="content" />
    </div>
  </Portal>
</div>

// src/components/Popover/index.tsx
import {
  createEffect,
  createSignal,
  JSX,
  JSXElement,
  onCleanup,
  onMount,
  Setter,
} from "solid-js";
import { CustomPortal } from "../CustomPortal";
import { upgradedSmartDropDown } from "../../utils";
import { cn } from "../../utils/class";

export type IPopOverSJContentPropType =
  | JSX.Element
  | (({ close }: { close: () => void }) => JSX.Element);

export type IPopOverPositionX = "left" | "right" | "center";
export type IPopOverPositionY = "top" | "bottom" | "auto";

interface PopoverProps {
  children: JSXElement;
  content: IPopOverSJContentPropType;
  positionX?: IPopOverPositionX;
  positionY?: IPopOverPositionY;
  useRefWidth?: boolean;
  isShown?: boolean;
  setIsShown?: Setter<boolean>;
  onClickOutside?: (e?: Event, isShown?: Setter<boolean>) => void;
  handleChildrenClick?: (setIsShown?: Setter<boolean>) => void;
  className?: string;
  onOpen?: () => void;
  onClose?: () => void;
  zIndex?: number;
  width?: JSX.CSSProperties["width"];
  contentClassName?: string;
}

export const Popover = (props: PopoverProps) => {
  const [top, setTop] = createSignal<string | undefined>();
  const [left, setLeft] = createSignal<string | undefined>();
  const [popoverRef, setPopoverRef] = createSignal<any>();
  const [elementRef, setElementRef] = createSignal<any>();
  const [shown, setShown] = createSignal(false);

  const [delayShown, setDelayShown] = createSignal(false);

  const positionDropDown = (position?: {
    x?: IPopOverPositionX;
    y?: IPopOverPositionY;
  }) => {
    if (!position) {
      position = {
        x: props.positionX || "center",
        y: props.positionY || "auto",
      };
    }
    const { left, top } = upgradedSmartDropDown({
      inputRef: elementRef,
      dropDownRef: popoverRef,
      positionX: position.x,
      positionY: position.y,
    });

    setLeft(left);
    setTop(top);
  };

  createEffect(() => {
    const onScroll = () => {
      if (!props.isShown && !shown()) return;
      positionDropDown({
        y: props.positionY || "auto",
        x: props.positionX || "center",
      });
    };
    document.addEventListener("scroll", onScroll);
    window.addEventListener("resize", onScroll);
    onCleanup(() => {
      document.removeEventListener("scroll", onScroll);
      window.removeEventListener("resize", onScroll);
    });
  });

  createEffect(() => {
    if (props.isShown || shown()) {
      setTimeout(() => {
        setDelayShown(true);
      }, 100);
    } else {
      setDelayShown(false);
    }
  });

  createEffect(() => {
    if (!props.isShown && !shown()) {
      props.onClose?.();
      return;
    }
    props.onOpen?.();
    positionDropDown();
  });

  createEffect(() => {
    if (!delayShown()) return;
    positionDropDown({
      y: props.positionY || "auto",
      x: props.positionX || "center",
    });
  });

  onMount(() => {
    const portalIsland = document.getElementById("portal-island");
    if (portalIsland) return;
    const div = document.createElement("div");
    div.id = "portal-island";
    document.body.appendChild(div);
  });

  const handleElementClick = () => {
    if (props.handleChildrenClick) {
      props.handleChildrenClick(props.setIsShown || setShown);
      return;
    }
    if (props.setIsShown) {
      props.setIsShown(!props.isShown);
    } else {
      setShown(!shown());
    }
  };

  const handleClose = () => {
    if (props.setIsShown) {
      props.setIsShown(false);
    } else {
      setShown(false);
    }
  };

  const renderContent = () => {
    if (typeof props.content === "function") {
      const content = props.content({ close: handleClose });
      return <div data-type="dropdown">{content}</div>;
    }

    return <div data-type="dropdown">{props.content}</div>;
  };

  return (
    <div
      onkeyup={(e) => {
        if (e.key === "Escape" && (props.isShown || shown())) {
          handleClose();
        }
      }}
    >
      <div
        style={{
          ...(props.width && { width: props.width || "100%" }),
        }}
        class={cn(props.className)}
        ref={setElementRef}
        onClick={handleElementClick}
      >
        {props.children}
      </div>

      <CustomPortal
        setIsShown={props.setIsShown || setShown}
        isShown={props.isShown || shown()}
        referenceId={"portal-island"}
        hideDefaultStyle
        onClickOutside={
          props.onClickOutside
            ? (e) => props.onClickOutside?.(e, props.setIsShown || setShown)
            : undefined
        }
        reference={elementRef}
        useRefWidth={props.useRefWidth}
        style={{
          "z-index": props.zIndex || 1000,
          position: "fixed",
          ...(top() && { top: top() }),
          ...(left() && { left: left() }),
        }}
      >
        <div
          class={`
            ${
              delayShown()
                ? `rn-translate-y-[0rem] rn-opacity-100`
                : `-rn-translate-y-[1rem] rn-opacity-0`
            }
            rn-duration-350 
            rn-delay-50
            rn-transition-transform
            rn-ease-in-out
            motion-reduce:rn-transition-none
        `}
          ref={setPopoverRef}
        >
          <div
            class={cn(
              `
            ${
              delayShown()
                ? `scale-100 rn-opacity-100`
                : `scale-90 rn-opacity-0`
            }
            rn-duration-350 
            rn-transition-opacity
            rn-ease-in-out
            motion-reduce:rn-transition-none
        `,
              props.contentClassName,
            )}
          >
            {renderContent()}
          </div>
        </div>
      </CustomPortal>
    </div>
  );
};
