// src/components/Button/index.tsx
import { Component, JSX } from "solid-js";
import { cn } from "../../utils";

interface ButtonProps extends JSX.DOMAttributes<HTMLButtonElement> {
  class?: string;
  setHeight?: boolean;
  disabled?: boolean;
  style?: JSX.CSSProperties;
  selected?: boolean;
  noButtonAnimation?: boolean;
}

export const Button: Component<ButtonProps> = (props) => {
  return (
    <button
      {...{ ...props, class: undefined }}
      class={cn(
        `
        rn-btn 
        rn-btn-ghost 
        ${props.setHeight ? "" : "rn-h-full"} 
        ${props.selected ? "" : "dark:hover:rn-bg-black-tie"}
        date-picker-main-btn 
        rn-min-h-0 
        rn-p-0
        motion-reduce:rn-no-animation
        motion-reduce:rn-transition-none
        `,
        {
          "rn-no-animation": props.noButtonAnimation,
        },
        props.class,
      )}
      data-type={"date-picker-main-btn"}
      type={"button"}
    >
      {props.children}
    </button>
  );
};

// svelte/src/lib/Button.svelte
<script lang="ts">
  import { cn } from '../../utils';
  import type { HTMLButtonAttributes } from 'svelte/elements'

  export let className: string;
  export let setHeight: boolean = true;
  export let disabled: boolean = false;
  export let style: string;
  export let selected: boolean = false;
  export let onClick: () => void;
  let showAnimation = true;

  interface ButtonAttributes extends Partial<HTMLButtonAttributes> {
      class?: string;
      setHeight?: boolean;
      disabled?: boolean;
      style?: string;
      selected?: boolean;
  }

    export let props: ButtonAttributes ;
</script>

<button
        {...props}
  class={cn(`
      rn-btn
      rn-btn-ghost
      rn-p-0
      rn-min-h-0
      date-picker-main-btn
      motion-reduce:rn-transition-none
    `,
    {
      'rn-no-animation': !showAnimation,
      'rn-h-full': !setHeight,
      'dark:hover:rn-bg-black-tie': !selected,
    },
    className
  )}
        style={style}
        data-type={"date-picker-main-btn"}
        type={"button"}
        on:click={onClick}
        {disabled}
>
    <slot></slot>
</button>

<style>
    /* Add your styles here */
</style>
